### ISSUE TITLE
Crash on create account for shares

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2485]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x

```
Thread 1 "mmex" received signal SIGSEGV, Segmentation fault.
ShareTransactionDialog::OnTextEntered (this=0x7fffffff92c0, event=...)
    at /home/nick/moneymanagerex/src/sharetransactiondialog.cpp:440
440	    if (!m_commission_ctrl->GetValue().empty())
(gdb) 
```

**Comment by vomikan** [comment]
```
Thread 1 "mmex" received signal SIGSEGV, Segmentation fault.
ShareTransactionDialog::OnTextEntered (this=0x7fffffffa150, event=...)
    at /home/nick/moneymanagerex/src/sharetransactiondialog.cpp:440
440	    if (!m_commission_ctrl->GetValue().empty())
(gdb) backtrace
#0  ShareTransactionDialog::OnTextEntered(wxCommandEvent&)
    (this=0x7fffffffa150, event=...)
    at /home/nick/moneymanagerex/src/sharetransactiondialog.cpp:440
#1  0x0000555555b4a1c9 in mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const (this=
    0x55555638cd90, handler=0x7fffffffa150, func=
    (void (wxEvtHandler::*)(wxEvtHandler * const, wxEvent &)) 0x555555bfa114 <ShareTransactionDialog::OnTextEntered(wxCommandEvent&)>, event=...)
    at /home/nick/moneymanagerex/src/mmex.cpp:197
#2  0x00007ffff6fa5ec1 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
    (event=..., handler=<optimized out>, entry=...) at ../include/wx/app.h:462
#3  wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (entry=..., handler=<optimized out>, event=...)
    at ../src/common/event.cpp:1390
#4  0x00007ffff6fa608b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (this=<optimized out>, event=..., self=self@entry=0x7fffffffa150)
    at ../src/common/event.cpp:1023
#5  0x00007ffff6fa670d in wxEvtHandler::TryHereOnly(wxEvent&)
    (this=0x7fffffffa150, event=...) at ../src/common/event.cpp:1612
#6  0x00007ffff6fa678f in wxEvtHandler::TryBeforeAndHere(wxEvent&)
    (event=..., this=0x7fffffffa150) at ../include/wx/event.h:3912
#7  wxEvtHandler::ProcessEventLocally(wxEvent&)
    (this=0x7fffffffa150, event=...) at ../src/common/event.cpp:1545
#8  0x00007ffff6fa6891 in wxEvtHandler::ProcessEvent(wxEvent&)
    (this=0x7fffffffa150, event=...) at ../src/common/event.cpp:1518
#9  0x00007ffff7afef2e in wxWindowBase::TryAfter(wxEvent&)
    (this=0x555556884030, event=...) at ../include/wx/window.h:840
#10 0x00007ffff7afef2e in wxWindowBase::TryAfter(wxEvent&)
    (this=0x555556cf5e70, event=...) at ../include/wx/window.h:840
#11 0x00007ffff6fa809b in wxEvtHandler::SafelyProcessEvent(wxEvent&)
    (this=<optimized out>, event=...) at ../src/common/event.cpp:1636
#12 0x00007ffff7b004a0 in wxWindowBase::HandleWindowEvent(wxEvent&) const
    (this=this@entry=0x555556cf5e70, event=...) at ../include/wx/window.h:840
#13 0x00007ffff7ae63e4 in wxTextEntryBase::SendTextUpdatedEvent(wxWindow*)
    (win=0x555556cf5e70) at ../src/common/textentrycmn.cpp:458
#14 0x00007ffff7981a4b in wxTextEntry::DoSetValue(wxString const&, int)
--Type <RET> for more, q to quit, c to continue without paging--
    (this=0x555556cf63d8, value=..., flags=<optimized out>)
    at ../src/gtk/textentry.cpp:680
#15 0x00007ffff797ca69 in wxTextEntryBase::SetValue(wxString const&)
    (value=..., this=0x555556cf63d8) at ../include/wx/textentry.h:41
#16 wxTextCtrlBase::SetValue(wxString const&) (value=..., this=0x555556cf5e70)
    at ../include/wx/textctrl.h:747
#17 wxTextCtrl::Create(wxWindow*, int, wxString const&, wxPoint const&, wxSize const&, long, wxValidator const&, wxString const&)
    (this=this@entry=0x555556cf5e70, parent=parent@entry=0x555556884030, id=id@entry=6805, value=..., pos=..., size=..., style=1536, validator=..., name=...)
    at ../src/gtk/textctrl.cpp:819
#18 0x00007ffff797d204 in wxTextCtrl::wxTextCtrl(wxWindow*, int, wxString const&, wxPoint const&, wxSize const&, long, wxValidator const&, wxString const&)
    (this=0x555556cf5e70, parent=0x555556884030, id=6805, value=..., pos=..., size=..., style=1536, validator=..., name=...) at ../src/gtk/textctrl.cpp:718
#19 0x00005555559bcbb5 in mmTextCtrl::mmTextCtrl(wxWindow*, int, wxString const&, wxPoint const&, wxSize const&, long, wxValidator const&, DB_Table_CURRENCYFORMATS_V1::Data const*, wxString const&)
    (this=0x555556cf5e70, parent=0x555556884030, id=6805, value=..., pos=..., size=..., style=1536, validator=..., currency=0x5555563a4cc0, name=...)
    at /home/nick/moneymanagerex/src/mmTextCtrl.h:40
#20 0x0000555555bf7628 in ShareTransactionDialog::CreateControls()
    (this=0x7fffffffa150)
    at /home/nick/moneymanagerex/src/sharetransactiondialog.cpp:234
#21 0x0000555555bf5c43 in ShareTransactionDialog::Create(wxWindow*, int, wxString const&, wxPoint const&, wxSize const&, long)
    (this=0x7fffffffa150, parent=0x7fffffffc800, id=-1, caption=..., pos=..., size=..., style=536877056)
    at /home/nick/moneymanagerex/src/sharetransactiondialog.cpp:106
#22 0x0000555555bf56d4 in ShareTransactionDialog::ShareTransactionDialog(wxWindow*, DB_Table_STOCK_V1::Data*)
    (this=0x7fffffffa150, parent=0x7fffffffc800, stock=0x55555665e6f8)
    at /home/nick/moneymanagerex/src/sharetransactiondialog.cpp:70
#23 0x0000555555c08a52 in mmStockDialog::CreateShareAccount(DB_Table_ACCOUNTLIST_V1::Data*, wxString const&)
    (this=0x7fffffffc800, stock_account=0x555556b2cb80, name=...)
    at /home/nick/moneymanagerex/src/stockdialog.cpp:535
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x0000555555c08580 in mmStockDialog::OnSave(wxCommandEvent&)
    (this=0x7fffffffc800) at /home/nick/moneymanagerex/src/stockdialog.cpp:510
#25 0x0000555555b4a1c9 in mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
    (this=0x55555638cd90, handler=0x7fffffffc800, func=
    (void (wxEvtHandler::*)(wxEvtHandler * const, wxEvent &)) 0x555555c079d6 <mmStockDialog::OnSave(wxCommandEvent&)>, event=...)
    at /home/nick/moneymanagerex/src/mmex.cpp:197
#26 0x00007ffff6fa5ec1 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
    (event=..., handler=<optimized out>, entry=...) at ../include/wx/app.h:462
#27 wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (entry=..., handler=<optimized out>, event=...)
    at ../src/common/event.cpp:1390
#28 0x00007ffff6fa608b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (this=<optimized out>, event=..., self=self@entry=0x7fffffffc800)
    at ../src/common/event.cpp:1023
#29 0x00007ffff6fa670d in wxEvtHandler::TryHereOnly(wxEvent&)
    (this=0x7fffffffc800, event=...) at ../src/common/event.cpp:1612
#30 0x00007ffff6fa678f in wxEvtHandler::TryBeforeAndHere(wxEvent&)
    (event=..., this=0x7fffffffc800) at ../include/wx/event.h:3912
#31 wxEvtHandler::ProcessEventLocally(wxEvent&)
    (this=0x7fffffffc800, event=...) at ../src/common/event.cpp:1545
#32 0x00007ffff6fa6891 in wxEvtHandler::ProcessEvent(wxEvent&)
    (this=0x7fffffffc800, event=...) at ../src/common/event.cpp:1518
#33 0x00007ffff7afef2e in wxWindowBase::TryAfter(wxEvent&)
    (this=0x5555569e30d0, event=...) at ../include/wx/window.h:840
#34 0x00007ffff6fa809b in wxEvtHandler::SafelyProcessEvent(wxEvent&)
    (this=<optimized out>, event=...) at ../src/common/event.cpp:1636
#35 0x00007ffff7b004a0 in wxWindowBase::HandleWindowEvent(wxEvent&) const
    (this=this@entry=0x5555569e30d0, event=...) at ../include/wx/window.h:840
#36 0x00007ffff792b7e2 in wxgtk_button_clicked_callback(GtkWidget*, wxButton*)
    (button=0x5555569e30d0) at ../src/gtk/button.cpp:38
#37 0x00007ffff5621a56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff5640b28 in g_signal_emit_valist ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff56410d3 in g_signal_emit ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff5c3f2ae in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff5c3f318 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff5621802 in g_closure_invoke ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff5635962 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff5640b9e in g_signal_emit_valist ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff56410d3 in g_signal_emit ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff5c3d754 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007ffff5eeea71 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff5621a56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007ffff5640b28 in g_signal_emit_valist ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#50 0x00007ffff56410d3 in g_signal_emit ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#51 0x00007ffff5d05f5c in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#52 0x00007ffff5624c56 in g_cclosure_marshal_VOID__BOXEDv ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#53 0x00007ffff5621a56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#54 0x00007ffff5640b28 in g_signal_emit_valist ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#55 0x00007ffff56410d3 in g_signal_emit ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#56 0x00007ffff5d02fa2 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#57 0x00007ffff5d045eb in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#58 0x00007ffff5d075d6 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#59 0x00007ffff5ccebb0 in gtk_event_controller_handle_event ()
    at /lib/x86_64-linux-gnu/libgtk-3.so.0
#60 0x00007ffff5e910fd in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#61 0x00007ffff5ee848b in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#62 0x00007ffff5621802 in g_closure_invoke ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#63 0x00007ffff5634f96 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#64 0x00007ffff564045d in g_signal_emit_valist ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#65 0x00007ffff56410d3 in g_signal_emit ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#66 0x00007ffff5e92bb3 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#67 0x00007ffff5d4e0b8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#68 0x00007ffff5d5036b in gtk_main_do_event ()
    at /lib/x86_64-linux-gnu/libgtk-3.so.0
#69 0x00007ffff5a38f79 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#70 0x00007ffff5a6c106 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#71 0x00007ffff5533fbd in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#72 0x00007ffff5534240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#73 0x00007ffff5534533 in g_main_loop_run ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#74 0x00007ffff5d4f30d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#75 0x00007ffff78c1025 in wxGUIEventLoop::DoRun() (this=0x5555567c6ee0)
    at ../src/gtk/evtloop.cpp:64
#76 0x00007ffff6e51841 in wxEventLoopBase::Run()
    (this=this@entry=0x5555567c6ee0) at ../src/common/evtloopcmn.cpp:90
#77 0x00007ffff7937728 in wxDialog::ShowModal() (this=0x7fffffffc800)
    at ../src/gtk/dialog.cpp:176
#78 0x0000555555c25e3e in mmStocksPanel::call_dialog(int) (this=
    0x5555566830b0, selectedIndex=3)
    at /home/nick/moneymanagerex/src/stockspanel.cpp:999
#79 0x0000555555c1e784 in mmStocksPanel::OnListItemActivated(int)
    (this=0x5555566830b0, selectedIndex=3)
    at /home/nick/moneymanagerex/src/stockspanel.cpp:389
#80 0x0000555555c1e62a in StocksListCtrl::OnListItemActivated(wxListEvent&)
    (this=0x555556c3c500, event=...)
    at /home/nick/moneymanagerex/src/stockspanel.cpp:371
#81 0x0000555555b4a1c9 in mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
    (this=0x55555638cd90, handler=0x555556c3c500, func=
    (void (wxEvtHandler::*)(wxEvtHandler * const, wxEvent &)) 0x555555c1e52c <StocksListCtrl::OnListItemActivated(wxListEvent&)>, event=...)
    at /home/nick/moneymanagerex/src/mmex.cpp:197
#82 0x00007ffff6fa5ec1 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
--Type <RET> for more, q to quit, c to continue without paging--
    (event=..., handler=<optimized out>, entry=...) at ../include/wx/app.h:462
#83 wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (entry=..., handler=<optimized out>, event=...)
    at ../src/common/event.cpp:1390
#84 0x00007ffff6fa608b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (this=<optimized out>, event=..., self=self@entry=0x555556c3c500)
    at ../src/common/event.cpp:1023
#85 0x00007ffff6fa670d in wxEvtHandler::TryHereOnly(wxEvent&)
    (this=0x555556c3c500, event=...) at ../src/common/event.cpp:1612
#86 0x00007ffff6fa678f in wxEvtHandler::TryBeforeAndHere(wxEvent&)
    (event=..., this=0x555556c3c500) at ../include/wx/event.h:3912
#87 wxEvtHandler::ProcessEventLocally(wxEvent&)
    (this=0x555556c3c500, event=...) at ../src/common/event.cpp:1545
#88 0x00007ffff6fa6891 in wxEvtHandler::ProcessEvent(wxEvent&)
    (this=0x555556c3c500, event=...) at ../src/common/event.cpp:1518
#89 0x00007ffff7b74d92 in wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
    (this=0x555556bc4730, event=...) at ../src/generic/scrlwing.cpp:200
#90 0x00007ffff790b3f6 in wxListMainWindow::SendNotify(unsigned long, int, wxPoint const&) (this=0x555556604bf0, line=3, command=<optimized out>, point=...)
    at ../include/wx/window.h:840
#91 0x00007ffff790f87f in wxListMainWindow::OnMouse(wxMouseEvent&)
    (this=0x555556604bf0, event=...) at ../src/generic/listctrl.cpp:2532
#92 0x0000555555b4a1c9 in mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
    (this=0x55555638cd90, handler=0x555556604bf0, func=
    (void (wxEvtHandler::*)(wxEvtHandler * const, wxEvent &)) 0x7ffff790f5d0 <wxListMainWindow::OnMouse(wxMouseEvent&)>, event=...)
    at /home/nick/moneymanagerex/src/mmex.cpp:197
#93 0x00007ffff6fa5ec1 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
    (event=..., handler=<optimized out>, entry=...) at ../include/wx/app.h:462
#94 wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (entry=..., handler=<optimized out>, event=...)
    at ../src/common/event.cpp:1390
#95 0x00007ffff6fa608b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (this=<optimized out>, event=..., self=self@entry=0x555556604bf0)
    at ../src/common/event.cpp:1023
--Type <RET> for more, q to quit, c to continue without paging--
#96 0x00007ffff6fa670d in wxEvtHandler::TryHereOnly(wxEvent&)
    (this=0x555556604bf0, event=...) at ../src/common/event.cpp:1612
#97 0x00007ffff6fa678f in wxEvtHandler::TryBeforeAndHere(wxEvent&)
    (event=..., this=0x555556604bf0) at ../include/wx/event.h:3912
#98 wxEvtHandler::ProcessEventLocally(wxEvent&)
    (this=0x555556604bf0, event=...) at ../src/common/event.cpp:1545
#99 0x00007ffff6fa6891 in wxEvtHandler::ProcessEvent(wxEvent&)
    (this=0x555556604bf0, event=...) at ../src/common/event.cpp:1518
#100 0x00007ffff6fa809b in wxEvtHandler::SafelyProcessEvent(wxEvent&)
    (this=<optimized out>, event=...) at ../src/common/event.cpp:1636
#101 0x00007ffff7b004a0 in wxWindowBase::HandleWindowEvent(wxEvent&) const
    (this=this@entry=0x555556604bf0, event=...) at ../include/wx/window.h:840
#102 0x00007ffff78e6200 in wxWindow::GTKProcessEvent(wxEvent&) const
    (event=..., this=0x555556604bf0) at ../src/gtk/window.cpp:1536
#103 gtk_window_button_press_callback(GtkWidget*, GdkEventButton*, wxWindow*)
    (gdk_event=0x555556a96ac0, win=0x555556604bf0)
    at ../src/gtk/window.cpp:1688
#104 0x00007ffff5ee848b in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#105 0x00007ffff5621802 in g_closure_invoke ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#106 0x00007ffff5635814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#107 0x00007ffff564045d in g_signal_emit_valist ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#108 0x00007ffff56410d3 in g_signal_emit ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#109 0x00007ffff5e92bb3 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#110 0x00007ffff5d4e0b8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#111 0x00007ffff5d5036b in gtk_main_do_event ()
    at /lib/x86_64-linux-gnu/libgtk-3.so.0
#112 0x00007ffff5a38f79 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#113 0x00007ffff5a6c106 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#114 0x00007ffff5533fbd in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#115 0x00007ffff5534240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#116 0x00007ffff5534533 in g_main_loop_run ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#117 0x00007ffff5d4f30d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#118 0x00007ffff78c1025 in wxGUIEventLoop::DoRun() (this=0x555556bb7f90)
    at ../src/gtk/evtloop.cpp:64
#119 0x00007ffff6e51841 in wxEventLoopBase::Run() (this=0x555556bb7f90)
    at ../src/common/evtloopcmn.cpp:90
#120 0x00007ffff6e1c01a in wxAppConsoleBase::MainLoop() (this=0x55555638cd90)
    at ../src/common/appbase.cpp:380
#121 0x00007ffff6ea665a in wxEntry(int&, wchar_t**)
    (argc=<optimized out>, argv=<optimized out>) at ../include/wx/app.h:462
#122 0x0000555555b490b2 in main(int, char**) (argc=1, argv=0x7fffffffdee8)
    at /home/nick/moneymanagerex/src/mmex.cpp:37
```

**Comment by vomikan** [comment]
Windows output:
```SQLITE_INSERT
database: main, table: PAYEE_V1, rowid: 1
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
1 -> 1
200.0000 -> 200,0000
0.0000 -> 0,0000
SQLITE_UPDATE
database: main, table: STOCK_V1, rowid: 1
200.00 -> 200,00
SQLITE_INSERT
database: main, table: CHECKINGACCOUNT_V1, rowid: 1
SQLITE_INSERT
database: main, table: TRANSLINK_V1, rowid: 1
SQLITE_UPDATE
database: main, table: CHECKINGACCOUNT_V1, rowid: 1
SQLITE_INSERT
database: main, table: SHAREINFO_V1, rowid: 1
SQLITE_UPDATE
database: main, table: STOCK_V1, rowid: 1
SQLITE_UPDATE
database: main, table: STOCKHISTORY_V1, rowid: 1
c:\wxwidgets\src\msw\window.cpp(594): 'SetFocus' failed with error 0x00000057 (Параметр задан неверно.).
=========== navTreeStateToJson =============================
{
    "item@Home Page": true,
    "item@Stocks": true
}
SQLITE_UPDATE
database: main, table: INFOTABLE_V1, rowid: 8
```

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/81841495-360f0680-9553-11ea-97cc-daf5b371bf9c.png)

**Comment by vomikan** [comment]
Fucking mystique
